FORMAT: 1A
HOST: http://sikolin.cloudapp.net/api/

# Sikolin

List of API that Sikolin provide

## Authentication [/auth.jsp]

### Login on Android [POST]

+ Request (application/x-www-form-urlencoded)

        username=tester&password=tester

    
+ Response 200 (application/json)

        {
            "authkey":"30dc08cd0ecce4fdc0706053a274b31a",
            "role":0,
            "credits":0,
            "status":true,
            "username":"tester"
        }

## Register [/reg.jsp]

### Register from Android [POST]

+ Request (application/x-www-form-urlencoded)

        username=tester&password=tester&role=0

    
+ Response 200 (application/json)

        {
            "message":"Thank you for register",
            "status":true
        }